### PR TITLE
screenshot.png is created by a test, does not need to be in git

### PR DESCRIPTION
**Pull request by beattie**
Minor cleanup.
Deleted screenshot.png and added it to .gitignore

### CODE REVIEW

**Comment by drahnr** [comment]
The idea is to keep the screenshot.png up to date in the repo, since it is referenced by the github README.md.
The .gitignore makes sense though, so I'd be happy if you could undelete the screenshot.png (or just rerun the `./waf ...`) and add that as another commit.

**Comment by beattie** [comment]
Actually, if you want to keep screen shot up to date.  Then I think the .gitignore needs more thought.  If the test-screenshot changes then you want to update the screen shot.  If add it to .gitignore then updating screenshot.png is likely to get forgotten.  screenshot.png will only get updated when you run the tests, (of course I like to run the tests).  The cost of unecessary updates to screenshot.png is a small number of bytes on each commit.  It's messier, (I like things neat) but screenshot.png will be up to date.  You could have a policy that screenchot.png should not be included in a commit unless test-screenshot has changed .and that it should removed manually.  Finally scheenshot.png changing is evidence that the commiter has run the test, not a bad idea.  I thing the pull request should be rejected.

**Comment by drahnr** [comment]
Good point, but in general the appearance should not change that much anymore.

If you add it to gitignore you can still force add it manually with git.

Another thing would be to save the screenshot to the build directory and copy it manually over.

What do you think?

**Comment by drahnr** [comment]
I alreadz fixed this in master, so I'll turn this down.

**Pull request closed without merging**
